version: '3.1'

services:

  localstack:
    image: localstack/localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - /localstack:/tmp/localstack
      # Uncomment if you want to not persist
      # - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

    healthcheck:
      test: curl --fail http://localhost:4566/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5